language: node_js
node_js:
  - "10.15.3"
script:
  -
install:
  - "npm install"
  - "gulp build"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "toolset-one-web"